services:
  zookeeper:
    environment:
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 10
      ZOOKEEPER_SYNC_LIMIT: 5
    mem_limit: 512m
    healthcheck:
      interval: 20s
      timeout: 10s
      retries: 15
      start_period: 60s

  kafka:
    mem_limit: 1g
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 90s

  yowyob-erp-backend:
    build:
      context: .
      dockerfile: Dockerfile_alternative  # on passe à une image qui marche toujours

