package com.yowyob.erp.accounting.domain.port.in;

import com.yowyob.erp.accounting.domain.model.Compte;
import com.yowyob.erp.accounting.domain.model.JournalAudit;
import com.yowyob.erp.accounting.domain.model.Organization;
import com.yowyob.erp.accounting.infrastructure.web.dto.CompteDto;
import com.yowyob.erp.accounting.infrastructure.web.dto.JournalAuditDto;
import com.yowyob.erp.shared.domain.exception.BusinessException;
import com.yowyob.erp.shared.domain.exception.ResourceNotFoundException;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.UUID;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

/**
 * Use case port defining the Compte operations.
 */
public interface CompteUseCase {
    Mono<CompteDto> createCompte(CompteDto dto);
    Flux<CompteDto> findAllByOrganization(UUID organization_id);
    Mono<CompteDto> findById(UUID organization_id, UUID id);
    Flux<CompteDto> findByNoCompte(UUID organization_id, String no_compte);
    Flux<CompteDto> getClientAccounts(UUID organization_id);
    Flux<CompteDto> getSupplierAccounts(UUID organization_id);
    Flux<CompteDto> getBankAccounts(UUID organization_id);
    Flux<CompteDto> getCashAccounts(UUID organization_id);
    Flux<CompteDto> getAccountsByType(UUID organization_id, String type);
    Mono<CompteDto> updateCompte(UUID organization_id, UUID id, CompteDto dto);
    Mono<Void> deleteById(UUID organization_id, UUID id);
    Mono<Void> updateBalances(UUID organization_id, UUID ecriture_id);
    Mono<CompteDto> createAutoGeneratedAccount(String name, String type, String notes, UUID externalId);
}
