package com.yowyob.erp.accounting.controller;

import com.yowyob.erp.accounting.dto.CompteDto;
import com.yowyob.erp.accounting.service.CompteService;
import com.yowyob.erp.common.dto.ApiResponseWrapper;
import com.yowyob.erp.config.tenant.ReactiveTenantContext;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import reactor.core.publisher.Mono;

import java.util.List;
import java.util.UUID;

import jakarta.validation.Valid;

/**
 * Reactive Controller for managing accounting accounts.
 */
@RestController
@RequestMapping("/api/accounting/comptes")
@Tag(name = "Accounting Comptes", description = "Endpoints for accounting account management")
@RequiredArgsConstructor
@Slf4j
public class CompteController {

        private final CompteService compte_service;

        /**
         * Creates a new accounting account.
         */
        @PostMapping
        @Operation(summary = "Create an accounting account")
        public Mono<ResponseEntity<ApiResponseWrapper<CompteDto>>> createCompte(@Valid @RequestBody CompteDto dto) {
                return compte_service.createCompte(dto)
                                .map(saved -> ResponseEntity.status(HttpStatus.CREATED)
                                                .body(ApiResponseWrapper.success(saved,
                                                                "Account created successfully")))
                                .contextWrite(ReactiveTenantContext.captureFromThreadLocal());
        }

        /**
         * Generates and creates an account based on a specific type (Client, Supplier,
         * etc.).
         */
        @PostMapping("/generate")
        @Operation(summary = "Generate and create an account based on type")
        public Mono<ResponseEntity<ApiResponseWrapper<CompteDto>>> createAutoGeneratedAccount(
                        @Valid @RequestBody com.yowyob.erp.accounting.dto.AccountGenerationRequestDto request) {

                log.info("Request to generate {} account for {}", request.getType(), request.getName());
                return compte_service
                                .createAutoGeneratedAccount(request.getName(), request.getType(), request.getNotes())
                                .map(saved -> ResponseEntity.status(HttpStatus.CREATED)
                                                .body(ApiResponseWrapper.success(saved,
                                                                "Account created successfully")))
                                .contextWrite(ReactiveTenantContext.captureFromThreadLocal());
        }

        /**
         * Retrieves all accounts for the current tenant.
         */
        @GetMapping
        @Operation(summary = "List all accounts")
        public Mono<ResponseEntity<ApiResponseWrapper<List<CompteDto>>>> getAllComptes() {
                return ReactiveTenantContext.getTenantId()
                                .flatMapMany(compte_service::findAllByTenant)
                                .collectList()
                                .map(comptes -> ResponseEntity
                                                .ok(ApiResponseWrapper.success(comptes,
                                                                "Accounts list retrieved successfully")))
                                .contextWrite(ReactiveTenantContext.captureFromThreadLocal());
        }

        /**
         * Retrieves an account by its ID.
         */
        @GetMapping("/{id}")
        @Operation(summary = "Get account by ID")
        public Mono<ResponseEntity<ApiResponseWrapper<CompteDto>>> getCompteById(@PathVariable UUID id) {
                return ReactiveTenantContext.getTenantId()
                                .flatMap(tenant_id -> compte_service.findById(tenant_id, id))
                                .map(compte -> ResponseEntity.ok(ApiResponseWrapper.success(compte, "Account found")))
                                .contextWrite(ReactiveTenantContext.captureFromThreadLocal());
        }

        /**
         * Searches for accounts by account number.
         */
        @GetMapping("/search")
        @Operation(summary = "Search accounts by account number")
        public Mono<ResponseEntity<ApiResponseWrapper<List<CompteDto>>>> findByNoCompte(
                        @RequestParam String no_compte) {
                return ReactiveTenantContext.getTenantId()
                                .flatMapMany(tenant_id -> compte_service.findByNoCompte(tenant_id, no_compte))
                                .collectList()
                                .map(comptes -> ResponseEntity
                                                .ok(ApiResponseWrapper.success(comptes, "Search results")))
                                .contextWrite(ReactiveTenantContext.captureFromThreadLocal());
        }

        /**
         * Retrieves all client accounts (411xxx).
         */
        @GetMapping("/clients")
        @Operation(summary = "Get all client accounts")
        public Mono<ResponseEntity<ApiResponseWrapper<List<CompteDto>>>> getClientAccounts() {
                return ReactiveTenantContext.getTenantId()
                                .flatMapMany(compte_service::getClientAccounts)
                                .collectList()
                                .map(comptes -> ResponseEntity
                                                .ok(ApiResponseWrapper.success(comptes, "Client accounts retrieved")))
                                .contextWrite(ReactiveTenantContext.captureFromThreadLocal());
        }

        /**
         * Retrieves all supplier accounts (401xxx).
         */
        @GetMapping("/suppliers")
        @Operation(summary = "Get all supplier accounts")
        public Mono<ResponseEntity<ApiResponseWrapper<List<CompteDto>>>> getSupplierAccounts() {
                return ReactiveTenantContext.getTenantId()
                                .flatMapMany(compte_service::getSupplierAccounts)
                                .collectList()
                                .map(comptes -> ResponseEntity
                                                .ok(ApiResponseWrapper.success(comptes, "Supplier accounts retrieved")))
                                .contextWrite(ReactiveTenantContext.captureFromThreadLocal());
        }

        /**
         * Retrieves all bank accounts (521xxx).
         */
        @GetMapping("/banks")
        @Operation(summary = "Get all bank accounts")
        public Mono<ResponseEntity<ApiResponseWrapper<List<CompteDto>>>> getBankAccounts() {
                return ReactiveTenantContext.getTenantId()
                                .flatMapMany(compte_service::getBankAccounts)
                                .collectList()
                                .map(comptes -> ResponseEntity
                                                .ok(ApiResponseWrapper.success(comptes, "Bank accounts retrieved")))
                                .contextWrite(ReactiveTenantContext.captureFromThreadLocal());
        }

        /**
         * Retrieves all cash accounts (571xxx).
         */
        @GetMapping("/cash")
        @Operation(summary = "Get all cash accounts")
        public Mono<ResponseEntity<ApiResponseWrapper<List<CompteDto>>>> getCashAccounts() {
                return ReactiveTenantContext.getTenantId()
                                .flatMapMany(compte_service::getCashAccounts)
                                .collectList()
                                .map(comptes -> ResponseEntity
                                                .ok(ApiResponseWrapper.success(comptes, "Cash accounts retrieved")))
                                .contextWrite(ReactiveTenantContext.captureFromThreadLocal());
        }

        /**
         * Retrieves accounts by type (ACTIF, PASSIF, CHARGE, PRODUIT, TAXE).
         */
        @GetMapping("/type/{type}")
        @Operation(summary = "Get accounts by type")
        public Mono<ResponseEntity<ApiResponseWrapper<List<CompteDto>>>> getAccountsByType(
                        @PathVariable String type) {
                return ReactiveTenantContext.getTenantId()
                                .flatMapMany(tenant_id -> compte_service.getAccountsByType(tenant_id, type))
                                .collectList()
                                .map(comptes -> ResponseEntity
                                                .ok(ApiResponseWrapper.success(comptes,
                                                                type + " accounts retrieved")))
                                .contextWrite(ReactiveTenantContext.captureFromThreadLocal());
        }

        /**
         * Updates an existing account.
         */
        @PutMapping("/{id}")
        @Operation(summary = "Update an account")
        public Mono<ResponseEntity<ApiResponseWrapper<CompteDto>>> updateCompte(@PathVariable UUID id,
                        @RequestBody CompteDto dto) {
                return ReactiveTenantContext.getTenantId()
                                .flatMap(tenant_id -> compte_service.updateCompte(tenant_id, id, dto))
                                .map(updated -> ResponseEntity.ok(
                                                ApiResponseWrapper.success(updated, "Account updated successfully")))
                                .contextWrite(ReactiveTenantContext.captureFromThreadLocal());
        }

        /**
         * Deletes an accounting account.
         */
        @DeleteMapping("/{id}")
        @Operation(summary = "Delete an account")
        public Mono<ResponseEntity<ApiResponseWrapper<String>>> deleteCompte(@PathVariable UUID id) {
                return ReactiveTenantContext.getTenantId()
                                .flatMap(tenant_id -> compte_service.deleteById(tenant_id, id))
                                .thenReturn(ResponseEntity
                                                .ok(ApiResponseWrapper.success("Account deleted successfully")))
                                .contextWrite(ReactiveTenantContext.captureFromThreadLocal());
        }
}
